feat: Migrate repository to TypeScript
ftrackhq/ftrack-web-widget pull request #4
Opened 2022-10-03 12:17 UTC by jimmycallin

- [ ] I have added automatic tests where applicable
- [x] The PR title is suitable as a release note
- [x] The PR contains a description of what has been changed
- [x] The description contains manual test instructions

## Changes

- Migrated ftrack-web-widget to TypeScript
- Uses same `tsconfig.json` as `yarn create vite` outputs when choosing a TypeScript project.
- Updates jsdoc comments to tsdoc.

## Test

- Check that it builds
- Check that `yarn lint` outputs typescript errors 
- Check that the config looks good
- Check that it outputs d.ts files and that they are picked up when used in other projects.

2022-10-04 03:24 UTC, WaylonFtrack requested changes

2022-10-07 21:25 UTC, jimmycallin commented on src/ftrackWidget.ts
> +type MessageContent = {
interesting, thanks!

2022-10-07 21:26 UTC, jimmycallin commented on .eslintrc
> +  "extends": ["react-app", "plugin:@typescript-eslint/recommended"],
we use eslint-config-react-app for linting in all our projects, even when they are not containing react as dependency. it's not ideal but preferable over having separate eslint configs to maintain.

2022-10-07 21:27 UTC, jimmycallin commented
@WaylonFtrack please review again!

2022-10-08 05:39 UTC, WaylonFtrack requested changes

2022-10-08 05:39 UTC, WaylonFtrack commented on src/ftrackWidget.ts
> +  ] as (keyof KeyboardEvent)[];
This writing feels a bit strange, maybe `Array<keyof KeyboardEvent>` is better?

2022-10-08 05:39 UTC, WaylonFtrack commented on src/ftrackWidget.ts
> +interface MessageContent {
these interface should be exported, it may be used by users.

2022-10-08 05:44 UTC, WaylonFtrack commented on src/ftrackWidget.ts
> +  ] as (keyof KeyboardEvent)[];
This writing feels a bit strange, maybe `Array<keyof KeyboardEvent>` is better?

2022-10-08 05:45 UTC, WaylonFtrack commented on src/ftrackWidget.ts
> +  const fields: (keyof KeyboardEvent)[] = [
This writing feels a bit strange, maybe `Array<keyof KeyboardEvent>` is better?

2022-10-09 19:10 UTC, jimmycallin commented
@WaylonFtrack thanks! please review again :)

2022-10-10 07:42 UTC, CzBiX approved these changes
LGTM

2022-10-10 07:44 UTC, WaylonFtrack approved these changes

2022-10-10 18:05 UTC, gismya requested changes
Very good! Just a few small comments.

I haven't checked if it actually works after the refactor though - I don't know enough about the package to do that.

2022-10-10 20:19 UTC, jimmycallin commented on src/ftrackWidget.ts
> +export function openSidebar(entityType: string, entityId: string) {
don't think it hurts!

2022-10-10 20:21 UTC, jimmycallin commented on src/ftrackWidget.ts
>    if (
no opinion from my part - kept it as it was in the implementation before, feels out of scope to make any changes outside required for typescript migration.

2022-10-10 20:23 UTC, jimmycallin commented
@gismya addressed your comments, please review again!

2022-10-11 07:26 UTC, gismya requested changes
Just want to land in whether we use the indexed access types for the functions. If we do that, also change navigate function, if not, roll back openSidebar function. Would love to hear if @WaylonFtrack has any thoughts on if that pattern makes sense.

2022-10-11 07:26 UTC, gismya commented on src/ftrackWidget.ts
>    const tagName = target?.tagName.toLowerCase();
The optional chaining after target is still unnecessary.

2022-10-11 07:26 UTC, gismya commented on src/ftrackWidget.ts
> +export function navigate(entityType: string, entityId: string, module: string) {
Same change as in openSidebar possible here, if we decide on going that route.

2022-10-11 07:26 UTC, gismya commented on src/ftrackWidget.ts
> +export function openSidebar(entityType: string, entityId: string) {
But does it help? Can't find much discussion online about it, and feels presumptuous to just go with my gut feeling on this (Seeing as it in some sense complicates the code)

2022-10-11 07:27 UTC, gismya commented on src/ftrackWidget.ts
> +export function openSidebar(entityType: string, entityId: string) {
![image](https://user-images.githubusercontent.com/8929526/195023261-9359ab10-7c24-4bc7-9e6b-e746de25a65f.png)

2022-10-11 07:43 UTC, gismya commented on src/ftrackWidget.ts
> +  if (!target || !(target instanceof HTMLElement)) return;
I also realised that `!(target instanceof HTMLElement)` is an implicit null check as well, but I feel it's probably more readable doing that null check "twice".

2022-10-11 07:47 UTC, CzBiX commented on src/ftrackWidget.ts
> +export function openSidebar(entityType: string, entityId: string) {
If we follow the textbook approach, then we should use the indexed type approach. This is particularly helpful for refactoring scenarios, such as `entityType.id` going from a `number` to a `string`.
But if this field is primitive type, I personally prefer to just use the primitive type, which is simpler to write and understand.

2022-10-11 08:24 UTC, WaylonFtrack commented on src/ftrackWidget.ts
> +export function openSidebar(entityType: string, entityId: string) {
If we follow the textbook approach, then we should use the indexed type approach. This is particularly helpful for refactoring scenarios, such as entity.id going from a number to a string.
But if this field is primitive type, I personally prefer to just use the primitive type, which is simpler to write and understand.

2022-10-11 19:25 UTC, jimmycallin commented
rolled back indexed type after weiran's feedback and removed the null check, please review again!

2022-10-12 08:13 UTC, gismya approved these changes

2022-10-12 13:06 UTC, emm4back approved these changes

2022-10-13 09:02 UTC, swetapadmanabhan approved these changes

2022-10-14 09:51 UTC, mertkirbuga approved these changes

2022-10-18 12:09 UTC, lucaas approved these changes
Tested and working well.

Added a few optional comments to the code. Read through before you merge.

2022-10-18 12:09 UTC, lucaas commented on src/ftrackWidget.ts
> +  const eventData: Partial<KeyboardEvent> = Object.fromEntries(
Doesn't looks like this get transpiled, so we are raising the requirement to browsers supporting [Object.fromEntries](https://caniuse.com/?search=fromEntries) and [arrow functions](https://caniuse.com/?search=arrow%20function).

Personally, I would have kept the for-loop, but I think the browser support is enough for this to be ok.

2022-10-19 07:43 UTC, jimmycallin commented on src/ftrackWidget.ts
> +/**
Not sure, I think I changed it mostly for consistency but don't really have a strong opinion. I'll keep it as is and won't change them in the future :)

2022-10-19 07:43 UTC, merged